package se.fk.rimfrost.framework.regel.error;

public class RegelFelkod
{
   public final static String RIMFROST_HANDLAGGNING_READ_FAILURE = "RIMFROST_HANDLAGGNING_READ_FAILURE";
   public final static String RIMFROST_HANDLAGGNING_WRITE_FAILURE = "RIMFROST_HANDLAGGNING_WRITE_FAILURE";
   public final static String RIMFROST_CLOUD_EVENT_DATA_READ_FAILURE = "RIMFROST_CLOUD_EVENT_DATA_READ_FAILURE";
   public final static String RIMFROST_CLOUD_EVENT_DATA_WRITE_FAILURE = "RIMFROST_CLOUD_EVENT_DATA_WRITE_FAILURE";
   public final static String RIMFROST_MANUELL_REGEL_COMMON_DATA_READ_FAILURE = "RIMFROST_MANUELL_REGEL_COMMON_DATA_READ_FAILURE";
   public final static String RIMFROST_MANUELL_REGEL_COMMON_DATA_WRITE_FAILURE = "RIMFROST_MANUELL_REGEL_COMMON_DATA_WRITE_FAILURE";
   public final static String RIMFROST_OUL_READ_FAILURE = "RIMFROST_OUL_READ_FAILURE";
   public final static String RIMFROST_OUL_WRITE_FAILURE = "RIMFROST_OUL_WRITE_FAILURE";
   public final static String RIMFROST_OUL_NOT_FOUND = "RIMFROST_OUL_NOT_FOUND";
   public final static String RIMFROST_PROCESS_TOPIC_INFO_READ_FAILURE = "RIMFROST_PROCESS_TOPIC_INFO_READ_FAILURE";
   public final static String RIMFROST_PROCESS_TOPIC_INFO_WRITE_FAILURE = "RIMFROST_PROCESS_TOPIC_INFO_WRITE_FAILURE";
   public final static String RIMFROST_OTHER = "RIMFROST_OTHER";
}
